services:

  ollama:
    image: ollama/ollama:latest
#    environment:
#      MODELS: "llama3.1:8b"
    ports:
      - "8080:11434"
    entrypoint: "/entrypoint.sh"
    volumes:
      - "./src/docker/ollama/entrypoint.sh:/entrypoint.sh"
