ai.category=AI connectors
connectorDefinitionDescription=Bonita connector: ${project.artifactId}-extract
connectorDefinitionLabel=Extract information from a document

defaultPage.pageTitle=Azure OpenAI Extract Connector configuration
defaultPage.pageDescription=Extract connector main configuration.

advancedPage.pageTitle=Azure OpenAI Extract Connector advanced configuration
advancedPage.pageDescription=Extract connector advanced configuration.

urlWidget.label=Azure OpenAI Endpoint
urlWidget.description=The Azure OpenAI endpoint URL. This is mandatory for Azure.

apiKeyWidget.label=Azure OpenAI API Key
apiKeyWidget.description=The API Key to use. Default to a system env lookup for a variable named AI_API_KEY.

chatModelNameWidget.label=Deployment name
chatModelNameWidget.description=The Azure OpenAI deployment name.

sourceDocumentRefWidget.label=Source document reference
sourceDocumentRefWidget.description=The reference of the process document from where to extract content.

modelTemperatureWidget.label=Model temperature
modelTemperatureWidget.description=The temperature to use for the model. Must be between 0 and 1.

requestTimeoutWidget.label=Request timeout
requestTimeoutWidget.description=The request timeout for Azure OpenAI calls.

fieldsToExtractWidget.label=Fields to extract
fieldsToExtractWidget.description=The list of fields to extract from the given document.

outputJsonSchemaWidget.label=Output JSON schema
outputJsonSchemaWidget.description=The JSON schema that represents how to structure the JSON connector output.

apiVersionWidget.label=API Version
apiVersionWidget.description=The Azure OpenAI API version to use (default: 2024-10-21).

sourceDocumentRefsWidget.label=Source document references
sourceDocumentRefsWidget.description=List of process document references to add as context. Use this for multiple documents.
