name: "Label PR"
on:
  pull_request:

permissions:
  contents: read

jobs:
  pr-labeler:
    permissions:
      contents: read # for TimonVS/pr-labeler-action to read config file
      pull-requests: write # for TimonVS/pr-labeler-action to add labels in PR
    runs-on: ubuntu-24.04
    steps:
      - name: Add labels to PR
        uses: actions/labeler@v5